<?php

use App\Models\User;
use Illuminate\Support\Facades\Hash;

test('user factory creates a valid user', function () {
    $user = User::factory()->make();

    expect($user)->toBeInstanceOf(User::class);
    expect($user->name)->toBeString();
    expect($user->email)->toContain('@');
    expect(Hash::check('password', $user->password))->toBeTrue();
});

test('user has fillable attributes', function () {
    $user = new User();
    $fillable = $user->getFillable();

    expect($fillable)->toContain('name');
    expect($fillable)->toContain('email');
    expect($fillable)->toContain('password');
});

test('user password is hidden from serialization', function () {
    $user = User::factory()->make();
    $hidden = $user->getHidden();

    expect($hidden)->toContain('password');
    expect($hidden)->toContain('remember_token');
});

test('user email is unique in factory', function () {
    $user1 = User::factory()->make();
    $user2 = User::factory()->make();

    expect($user1->email)->not->toBe($user2->email);
});

test('user password is hashed in factory', function () {
    $user = User::factory()->make();

    expect(Hash::check('password', $user->password))->toBeTrue();
    expect($user->password)->not->toBe('password');
});

test('user email is verified in factory', function () {
    $user = User::factory()->make();

    expect($user->email_verified_at)->not->toBeNull();
});

test('user can be made with custom name', function () {
    $user = User::factory()->make(['name' => 'John Doe']);

    expect($user->name)->toBe('John Doe');
    expect($user->id)->toBeNull();
});

test('user email contains valid email format', function () {
    $user = User::factory()->make();

    expect($user->email)->toMatch('/^[^\s@]+@[^\s@]+\.[^\s@]+$/');
});

test('user name is not empty in factory', function () {
    $user = User::factory()->make();

    expect($user->name)->not->toBeEmpty();
    expect(strlen($user->name))->toBeGreaterThan(0);
});

test('user can be made with custom attributes', function () {
    $user = User::factory()->make(['name' => 'Test User', 'email' => 'test@example.com']);

    expect($user->name)->toBe('Test User');
    expect($user->email)->toBe('test@example.com');
    expect($user->id)->toBeNull();
});

test('user has timestamp casting for email_verified_at', function () {
    $user = User::factory()->make();
    $casts = $user->getCasts();

    expect($casts)->toHaveKey('email_verified_at');
    expect($casts['email_verified_at'])->toBe('datetime');
});

test('user password is casted as hashed', function () {
    $user = User::factory()->make();
    $casts = $user->getCasts();

    expect($casts)->toHaveKey('password');
    expect($casts['password'])->toBe('hashed');
});

test('multiple users have different emails', function () {
    $users = User::factory(5)->make();

    $emails = $users->map(fn ($user) => $user->email)->toArray();
    $uniqueEmails = array_unique($emails);

    expect(count($emails))->toBe(5);
});

test('user can be made with custom email and password', function () {
    $customEmail = 'custom@test.com';
    $user = User::factory()->make([
        'email' => $customEmail,
        'password' => Hash::make('custom-password')
    ]);

    expect($user->email)->toBe($customEmail);
    expect(Hash::check('custom-password', $user->password))->toBeTrue();
});

test('user factory state can be customized', function () {
    $user = User::factory()->make([
        'name' => 'Custom Name',
        'email' => 'custom@domain.com'
    ]);

    expect($user->name)->toBe('Custom Name');
    expect($user->email)->toBe('custom@domain.com');
});

test('user remember token is generated by factory', function () {
    $user = User::factory()->make();

    expect($user->remember_token)->not->toBeNull();
    expect(is_string($user->remember_token))->toBeTrue();
});

test('user is authenticatable', function () {
    $user = User::factory()->make();

    expect($user)->toBeInstanceOf(\Illuminate\Foundation\Auth\User::class);
});

test('user has notifiable trait', function () {
    $user = User::factory()->make();

    expect(method_exists($user, 'notify'))->toBeTrue();
});
